name: BukCommands
main: nl.sheepcraft.bukcommands.Main
version: ${project.version}
author: samschaap
commands:
  broadcast:
    description: Broadcast command.
    permission: bukcommands.broadcast
    usage: /<command> <message>
  spawn:
    description: Spawn command.
    permission: bukcommands.spawn
    usage: /<command>
  workbench:
    description: Workbench command.
    permission: bukcommands.workbench
    usage: /<command>
  gm:
    description: Gamemode command.
    permission: bukcommands.gm
    usage: /<command> <mode>
  fly:
    description: Fly command.
    permission: bukcommands.fly
    usage: /<command>
  skull:
    description: Skull command.
    permission: bukcommands.skull
    usage: /<command> <player>
  heal:
    description: Heal command.
    permission: bukcommands.heal
    usage: /<command> <player>
  resourcedl:
    description: Resourcedl command.
    permission: bukcommands.resourcedl
    usage: /<command> <url>
  fakeop:
    description: Fakeop command.
    permission: bukcommands.fakeop
    usage: /<command> <player>
  fakedeop:
    description: Fakedeop command.
    permission: bukcommands.fakedeop
    usage: /<command> <player>
permissions:
   bukcommands.broadcast:
     description: Broadcast command.
     default: op
   bukcommands.spawn:
     description: Spawn command.
     default: op
   bukcommands.workbench:
     description: Workbench command.
     default: op
   bukcommands.gm:
     description: Gamemode command.
     default: op
   bukcommands.fly:
     description: Fly command.
     default: op
   bukcommands.skull:
     description: Skull command.
     default: op
   bukcommands.heal:
     description: Heal command.
     default: op
   bukcommands.resourcedl:
     description: Resourcedl command.
     default: op
   bukcommands.fakeop:
     description: Fakeop command.
     default: op
   bukcommands.fakedeop:
     description: Fakedeop command.
     default: op